feat(Elife): Use link to executable for social media sharing
stencila/thema pull request #232
Opened 2020-08-18 16:03 UTC by nlisgo

2020-08-18 16:04 UTC, nlisgo commented on src/themes/elife/lib/downloads.ts
> +const deriveUrl = (type: string, id: string): string => {
This is unrelated but the 3rd parameter is no longer necessary.

2020-08-18 18:30 UTC, nlisgo commented
This is a followup to https://github.com/stencila/thema/pull/231. This will be marked as `Ready for review` once that has been merged in.

2020-08-19 08:59 UTC, discodavey requested changes
Looks good but cannot see the executables when clicking the links in the Socials. Is this correct?

2020-08-19 09:41 UTC, nlisgo commented
> Looks good but cannot see the executables when clicking the links in the Socials. Is this correct?

This is significant actually because the media card may not be too interesting for iframe content (not sure on this) but we can look at that after the launch? Currently, the executables are not publicly accessible so this is the main reason why the media card will not be great.

2020-08-19 09:57 UTC, discodavey commented
@nlisgo That's what I thought. I will pass it on what I can see with the code then.

2020-08-19 09:58 UTC, discodavey approved these changes

2020-08-19 09:59 UTC, merged

2020-08-20 12:08 UTC, nlisgo commented
@alex-ketch we can see this change yet: https://elife.stencila.io/article-30274/

2020-08-20 15:38 UTC, alex-ketch commented
@nlisgo We added caching of the Thema version number to the Hub to avoid network redirects and improve page load times.
The changes from this PR are now visible at the above link (https://elife.stencila.io/article-30274/), and I'll log an issue in the Hub to make sure these changes are distributed faster.

2020-08-20 15:42 UTC, nlisgo commented
I can't see the changes yet. I will let you know if it is still an issue tomorrow morning.