fix(RPNG): Increase subtedly of affordance
stencila/thema pull request #267
Opened 2020-12-04 04:03 UTC by nokome

This make the affordances on `CodeChunks` and `CodeExpressions` in RNGs much more subtle, showing only a green dot in the top left corner (middle-left for expressions) and reducing whitespace around them. The intent is to create images that are close to those that will appear in a published article but with an indicator that something can be done with them. In the future we might use a red square instead for code elements that have an error on them.

### Before

![image](https://user-images.githubusercontent.com/1152336/101119943-528aa180-3651-11eb-8464-f64fe4a97d8f.png)

### After

![image](https://user-images.githubusercontent.com/1152336/101119977-66360800-3651-11eb-9976-2cfa77ba9774.png)

### Before

![image](https://user-images.githubusercontent.com/1152336/101120046-84036d00-3651-11eb-9749-885a074cc56f.png)

### After

![image](https://user-images.githubusercontent.com/1152336/101120078-954c7980-3651-11eb-8c66-2dab4f40a083.png)

I have done more realistic tests going from `ipynb` to `docx` to `gdoc` and am happy with the final result: (note that the size of the "no output" dot is larger in the `docx` when Pandoc generates that file, maybe has some minimum size on images?)

![image](https://user-images.githubusercontent.com/1152336/101120314-320f1700-3652-11eb-8aaa-cbcfd7cf4883.png)

2020-12-04 17:47 UTC, alex-ketch commented
Thanks for this @nokome, I like the intention of this PR but have couple of objections with the changes as they currently are.

Design wise, I think we need to include some sort of border or container around the image. Otherwise the green dot becomes free-floating in space and feels completely detached from the figure. This is especially noticeable with the larger plots/heatmaps.

Second is about the usability and recognition of the dots. I think we can adjust the contrast a tad to make it more accessible for low-vision users, without becoming too prominent on the page.
I also think we need to be a bit more direct with what the symbol indicates. Given the contexts where these images will live (Word, GDocs, etc.), I don't think we can expect the reader to understand what the symbol indicates. To fix this I'd suggest either a small text label, a "code" icon, or ideally both.

2020-12-04 17:47 UTC, alex-ketch requested changes
Thanks for this @nokome, I like the intention of this PR but have couple of objections with the changes as they currently are.

Design wise, I think we need to include some sort of border or container around the image. Otherwise the green dot becomes free-floating in space and feels completely detached from the figure. This is especially noticeable with the larger plots/heatmaps.

Second is about the usability and recognition of the dots. I think we can adjust the contrast a tad to make it more accessible for low-vision users, without becoming too prominent on the page.
I also think we need to be a bit more direct with what the symbol indicates. Given the contexts where these images will live (Word, GDocs, print, etc.), I don't think we can expect the reader to understand what the symbol indicates. To fix this I'd suggest either a small text label, a "code" icon, or ideally both.

What do you think about the above suggestions?

2020-12-04 17:48 UTC, alex-ketch commented on src/themes/rpng/styles.css
> +  and thet should have a minimum size. */
```suggestion
  and they should have a minimum size. */
```

2020-12-04 19:40 UTC, nokome commented
Thanks @alex-ketch I'd be grateful if you could take this over. In response to your points...

> Design wise, I think we need to include some sort of border or container around the image. Otherwise the green dot becomes free-floating in space and feels completely detached from the figure. This is especially noticeable with the larger plots/heatmaps.

Personally, putting my user hat on, I prefer not to have a border around the image. I want the image to look just like a conventional plot or table that I may have copy and pasted in but with an icon that tells me it's actually generated from code that is editable and executable. I can click on the icon and see the image it is connected to:

![Peek 2020-12-05 08-13](https://user-images.githubusercontent.com/1152336/101205821-1009a900-36d3-11eb-90e6-474c86edb338.gif)

This would be good to do some user testing on and / or make it a user configurable option. For example in GoogleDocs you can add borders of varying width, colors and styles and GSuita could let the user decide the style of borders to add to code chunks etc. It is obviously a lot easier to add / remove borders at this point, rather than bake a particular border style into the image.

> Second is about the usability and recognition of the dots. I think we can adjust the contrast a tad to make it more accessible for low-vision users, without becoming too prominent on the page.
I also think we need to be a bit more direct with what the symbol indicates. Given the contexts where these images will live (Word, GDocs, print, etc.), I don't think we can expect the reader to understand what the symbol indicates. To fix this I'd suggest either a small text label, a "code" icon, or ideally both.

Yes, I agree, as long as the symbol can be kept relatively discrete. For consistency, I would be in favour of having a different symbols for math nodes which can be applied to `MathFragment` and `MathBlock` type nodes.

Another consideration here is the round trip conversion of rPNGs for code chunks (for example embedded in a Word document) that contain a single image output. For these, to keep the size of the rPNG to a minimum, we use a custom dataURI: `data:self` during encoding:

```ts
    // Special handling for nodes that already have an image as output.
    // For these, we do not want to repeat the image within a chunk
    // within the image. Instead we make it self-referencing.
    let transformed = node
    if (schema.isA('CodeChunk', node)) {
      const { outputs, ...rest } = node
      if (outputs?.length === 1) {
        const output = outputs[0]
        if (schema.isA('ImageObject', output)) {
          const { contentUrl, ...other } = output
          transformed = schema.codeChunk({
            ...rest,
            outputs: [
              schema.imageObject({
                contentUrl: 'data:self',
                ...other,
              }),
            ],
          })
        }
      }
    }
```

When _decoding_ we then look for images that use `data:self` and reconstitute them "from themselves":

```ts
  return transformSync(root, (node) => {
    if (schema.isA('ImageObject', node)) {
      const { contentUrl } = node
      if (contentUrl === 'data:self') {
        return {
          ...node,
          contentUrl: `data:image/png;base64,${buffer.toString('base64')}`,
        }
      }
    }
    return node
  })
```

Anywho, what this means is that when styling the outputs of `CodeChunk` nodes we need to avoid padding and margin otherwise we end up with a extra space and an extra dot when we do `encode > decode > encode` (without any execution in between) e.g. from https://github.com/stencila/encoda/blob/6ce814cc7bdda75bce0fa948809fac1546a06fae/src/codecs/rpng/rpng.test.ts#L94

![r-code-chunk-image-output-b](https://user-images.githubusercontent.com/1152336/101207151-0f721200-36d5-11eb-9722-b4263a0e3572.png)

2020-12-04 20:12 UTC, alex-ketch commented
> Thanks @alex-ketch I'd be grateful if you could take this over.

Sure thing, will propose some adjustments.

2020-12-07 22:46 UTC, alex-ketch approved these changes

2020-12-07 22:49 UTC, alex-ketch commented
Feel free to merge at will @nokome, as discussed these changes will require adjustments in Encoda to capture ~8px left margin of the target node.

2020-12-08 06:34 UTC, nokome commented
Thanks for finishing this off @alex-ketch !

2020-12-08 06:34 UTC, merged